import type { NextPage } from 'next'
import Head from 'next/head';
import { Button } from '../components';
import Header from '../layout/Header/Header';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Button icon='phone' appearance="primary">Call Group</Button>
        <Button icon='message' appearance="secondary">Watch Now</Button>
        <Button appearance="secondary">Watch Now</Button>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Qui illo quam natus voluptates dignissimos fuga, suscipit minus eius! Iure itaque delectus at mollitia. Quo expedita, temporibus commodi dolore delectus non!</p>
      </main>

      <footer>

      </footer>
    </div>
  )
}

export default Home
